version: 2

sources:
  - name: silverscreen
    description: "Source tables for SilverScreen Project"
    database: silverscreen
    schema: public
    tables:
      - name: invoices
        description: "Invoices issued for showing a specific movie at various theater locations during different months. Data was passed by 'Silver Screen' accountants."
        columns:
          - name: invoice_id
            description: "Unique identifier for each invoice."
            tests:
              - not_null
              - unique:
                  severity: warn
          - name: movie_id
            description: "Identifier for the movie being screened."
            tests:
              - not_null
          - name: month
            description: "The month in which the invoice was issued."
            tests:
              - not_null
          - name: location_id
            description: "The identifier of the movie theater location, which is where the movie was shown."
            tests:
              - not_null
          - name: studio
            description: "The production studio responsible for the movie, such as Pixar, Marvel Studios, etc."
            tests:
              - not_null
          - name: release_date
            description: "The official release date of the movie, when it was first available to the public in theaters."
            tests:
              - not_null
          - name: weekly_price
            description: "The weekly price charged for showing the movie at the specific location."
            tests:
              - not_null
          - name: total_invoice_sum
            description: "The total sum of the invoice for the month, typically calculated as the weekly price multiplied by the number of weeks or total shows."
            tests:
              - not_null
      - name: movie_catalogue
        description: "Detailed information about movies released in 2024 and rented out by 'Silver Screen'."
        columns:
          - name: movie_id
            description: "Unique identifier for each movie."
            tests:
              - unique
              - not_null
          - name: movie_title
            description: "Title of the movie."
            tests:
              - not_null
          - name: release_date
            description: "The official release date of the movie in YYYY-MM-DD format."
            tests:
              - not_null
          - name: genre
            description: "The genre of the movie, describing the type of content."
          - name: country
            description: "The country where the movie was produced."
            tests:
              - not_null
          - name: studio
            description: "The production studio responsible for making the movie."
            tests:
              - not_null
          - name: budget
            description: "The production budget of the movie, typically in dollars."
            tests:
              - not_null
          - name: director
            description: "The director of the movie."
            tests:
              - not_null
          - name: rating
            description: "The movie's age rating, describing the appropriate audience (e.g., PG, R)."
          - name: minutes
            description: "The runtime of the movie in minutes."
      - name: nj_001
        description: "Information on all transactions from location Number 1."
        columns:
          - name: transaction_id
            description: "A unique alphanumeric identifier assigned to each transaction. This ensures each transaction is uniquely identified."
            tests:
              - unique
              - not_null
          - name: timestamp
            description: "The date and time the transaction occurred, formatted as YYYY-MM-DD."
            tests:
              - not_null
          - name: movie_id
            description: "A unique identifier for the movie being viewed in the transaction, usually tied to the movie's ID."
            tests:
              - not_null
          - name: ticket_amount
            description: "The number of tickets purchased in this particular transaction."
            tests:
              - not_null
          - name: price
            description: "The price per ticket for the transaction. This is the cost of a single ticket."
            tests:
              - not_null
          - name: transaction_total
            description: "The total amount of money spent in the transaction, calculated as ticket_amount * price."
            tests:
              - not_null
          - name: is_discounted
            description: "A boolean value indicating whether the transaction involved a discounted ticket. TRUE for discounted, FALSE for full price."
            tests:
              - not_null
          - name: is_3d
            description: "A boolean value indicating whether the movie shown was in 3D. TRUE if the movie was in 3D, FALSE if not."
            tests:
              - not_null
      - name: nj_002
        description: "Information on all transactions from location Number 2."
        columns:
          - name: movie_id
            description: "A identifier for the movie being sold, typically tied to a movie's ID."
            tests:
              - not_null
          - name: date
            description: "The date of the ticket sales transaction, formatted as YYYY-MM-DD. This represents the day for which ticket sales are recorded."
            tests:
              - not_null
          - name: ticket_amount
            description: "The number of tickets sold on the given day."
            tests:
              - not_null
          - name: ticket_price
            description: "The price per ticket sold on that particular day."
            tests:
              - not_null
          - name: total_earned
            description: "The total revenue earned from ticket sales on the specified date, calculated as ticket_amount * ticket_price."
            tests:
              - not_null
      - name: nj_003
        description: "Information on all transactions from location Number 3, covering various product types such as tickets, snacks, drinks, etc."
        columns:
          - name: transaction_id
            description: "A unique alphanumeric identifier assigned to each transaction, ensuring that each transaction can be uniquely identified."
            tests:
              - unique
              - not_null
          - name: timestamp
            description: "The date and time when the transaction occurred, formatted as YYYY-MM-DD."
            tests:
              - not_null
          - name: product_type
            description: "The type of product involved in the transaction, which could be a ticket, drink, snack, etc."
            tests:
              - not_null
          - name: details
            description: "For tickets, this indicates the movie being viewed, represented by the movie_id. For other products, it remains empty or unspecified."
          - name: amount
            description: "The quantity of the product purchased in the transaction."
            tests:
              - not_null
          - name: price
            description: "The price per unit of the product sold. This is the cost of one item, whether it's a ticket, drink, or snack."
            tests:
              - not_null
          - name: total_value
            description: "The total amount spent in the transaction, calculated as amount * price."
            tests:
              - not_null

models:
  - name: invoices_clean
    description: "Cleaned (removed 3 duplicate values) invoices dataset."
    columns:
      - name: movie_id
        description: "An identifier for each movie"
        tests:
          - not_null
      - name: month
        description: "The month in which the invoice was issued, in the format YYYY-MM-DD."
        tests:
          - not_null
      - name: total_invoice_sum
        description: "The total sum of the invoice for the month"
        tests:
          - not_null
      - name: location_id
        description: "A unique identifier for each movie"
        tests:
          - not_null
  - name: movie_catalogue_clean
    description: "Cleaned movies_catalogue dataset: NULL values replaced with 'Unknown' in genre column; selected only necessary columns."
    columns:
      - name: movie_id
        description: "An identifier for each movie"
        tests:
          - not_null
          - unique
      - name: movie_title
        description: "Title of the movie."
        tests:
          - not_null
      - name: genre
        description: "The genre of the movie, describing the type of content."
      - name: studio
        description: "The production studio responsible for making the movie."
        tests:
          - not_null
  - name: nj_001_clean
    description: "Cleaned information on all transactions from location Number 1."
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: transaction_total
        tests:
          - not_null
      - name: location
        tests:
          - not_null
  - name: nj_002_clean
    description: "Cleaned information on all transactions from location Number 2."
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: transaction_total
        tests:
          - not_null
      - name: location
        tests:
          - not_null
  - name: nj_003_clean
    description: "Cleaned information on all transactions from location Number 3."
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: transaction_total
        tests:
          - not_null
      - name: location
        tests:
          - not_null
  - name: movie_metrics
    description: "A UNION between nj_001_clean, nj_002_clean and nj_003_clean"
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: transaction_total
        tests:
          - not_null
      - name: location
        tests:
          - not_null
  - name: movie_metrics_expanded
    description: "Joining movie_metrics and invoices_clean; aggregating to get rental_cost and revenue."
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: rental_cost
        tests:
          - not_null
      - name: location
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
  - name: silverscreen_report
    description: "The final table with all the aggregated and cleaned values ready for reporting and analysis."
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: movie_title
        tests:
          - not_null
      - name: genre
      - name: studio
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: location
        tests:
          - not_null
      - name: rental_cost
        tests:
          - not_null
      - name: tickets_sold
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null